language: rust
cache: cargo
dist: trusty
sudo: false
rust:
  - beta # FIXME: back to stable once edition 2018 released
  - nightly

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

env:
  global:
    - RUST_BACKTRACE="1"

script:
    - rustup update
    - rustup component add clippy-preview
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo test --all --verbose
