[package]
name = "witnet"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
publish = false
repository = "witnet/rust-witnet"
readme = "README.md"
license-file = "LICENSE"
keywords = ["witnet", "bloackchain", "smart-contracts", "dag", "cryptocurrency", "crypto", "oracles", "protocol", "p2p", "rust"]
description = "An in-progress open source implementation of the Witnet protocol written in Rust."

[workspace]
members = ["config", "core", "crypto", "data_structures", "p2p", "storage"]

[badges]
travis-ci = { repository = "https://github.com/witnet/rust-witnet", branch = "master" }

[dependencies]
clap = "2.31"
ctrlc = "3.1.1"
env_logger = "0.5.13"
log = "0.4.5"
just = "0.3.12"
toml = "0.4.6"
serde_json = "1.0.28"


witnet_config = { path = "./config" }
witnet_core = { path = "./core" }
witnet_crypto = { path = "./crypto" }
witnet_data_structures = { path = "./data_structures" }
witnet_p2p = { path = "./p2p" }
witnet_storage = { path = "./storage" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
