# Address of the witnet node JSON-RPC server
witnet_jsonrpc_addr = "127.0.0.1:1234"
# Url of the ethereum client
eth_client_url = "http://127.0.0.1:8545"
# Address of the WitnetBridgeInterface deployed contract
wbi_contract_addr = "0x49824bd89338C26Ea204F20AcbAd404CFeAB3301"
# Address of the BlockRelay deployed contract
block_relay_contract_addr = "0x1D774D4D7EC51B111EFE48EB5D53022C3e9CC4Af"
# Ethereum account used to create the transactions
eth_account = "0x20E56DAc7582782584c46061F382812D502Dd139"
# Enable block relay from witnet to ethereum?
enable_block_relay = true
# Enable data request claim + inclusion
enable_claim_and_inclusion = true
# Enable data request result reporting
enable_result_reporting = true
# Post data request more than once? Useful to retry if the data request
# was not included in a block
post_to_witnet_more_than_once = true
# Subscribe to witnet blocks? This is only necessary for block relay
subscribe_to_witnet_blocks = true
# Period to check for new blocks in block relay
block_relay_polling_rate_ms = 30_000
# Period to check for resolved data request using the witnet `dataRequestReport`
# method
witnet_dr_report_polling_rate_ms = 20_000
# Period to try to claim old data request whose claim expired
claim_dr_rate_ms = 30_000
# Period to check for new Ethereum events
eth_event_polling_rate_ms = 1_000
