# You can read more about all the configuration params in
# https://docs.witnet.io/configuration/toml-file/
[connections]
server_addr = "127.0.0.1:21337"
known_peers = ["40.121.131.135:21337"]
outbound_limit = 1
bootstrap_peers_period_seconds = 15

[storage]
db_path = ".wit"

[consensus_constants]
checkpoint_zero_timestamp = 1548855420

#########################################
### LOGGING CONFIGURATION             ###
#########################################

[logging]

# Whether to log to stdout
log_to_stdout = true

# Log level for stdout: Critical, Error, Warning, Info, Debug, Trace
stdout_log_level = "Info"

# Whether to log to a file
log_to_file = true

# Log level for file: Critical, Error, Warning, Info, Debug, Trace
file_log_level = "Info"

# Log file path
log_file_path = "wit.log"

# Whether to append to the log file (true), or replace it on every run (false)
log_file_append = true
