# Address of the witnet node JSON-RPC server
witnet_jsonrpc_addr = "127.0.0.1:21338"
# Url of the ethereum client
eth_client_url = "http://127.0.0.1:8888"
# Address of the WitnetRequestsBoard deployed contract
wrb_contract_addr = "0x354B08f9fD4b171e774898261908DfeA113b0e14"
# Address of the BlockRelay deployed contract
block_relay_contract_addr = "0xEaA9e7Ea612b169f5b41cfF86dA6322f57264a19"
# Ethereum account used to create the transactions
eth_account = "0x333b18f64949C59Cd0b84b51C7580f260c563c31"
# Period to check for new requests in the WRB
eth_new_dr_polling_rate_ms = 1_000

# Running in the witnet testnet?
witnet_testnet = false

# Gas limits for some methods.
# To let the client estimate, comment out the fields
[gas_limits]
post_data_request = 10000000
report_result = 2000000

[storage]
db_path = ".witnet_bridge/storage"
