# Address of the witnet node JSON-RPC server
witnet_jsonrpc_addr = "127.0.0.1:21336"
# Url of the ethereum client
eth_client_url = "http://127.0.0.1:8544"
# Address of the WitnetRequestsBoard deployed contract
wrb_contract_addr = "0x90d08bF4e89C9D1fFb69cb4F783c38F6493ae74a"
# Address of a Request Example deployed contract
request_example_contract_addr = "0xEaA9e7Ea612b169f5b41cfF86dA6322f57264a19"
# Ethereum account used to create the transactions
eth_account = "0xa550Cf4F03Bd2417Cf83c8a652703cdC33c016ee"
# Period to check for new requests in the WRB
eth_new_dr_polling_rate_ms = 1_000
# Period to check for completed requests in Witnet
wit_tally_polling_rate_ms = 45_000
# Period to post new requests to Witnet
wit_dr_sender_polling_rate_ms = 45_000

# Max value that will be accepted in a data request
# This is the maximum amount that the relayer is willing to lose per one data request
max_dr_value_nanowits = 100_000_000_000

# Running in the witnet testnet?
witnet_testnet = true

# Gas limits for some methods.
# To let the client estimate, comment out the fields
[gas_limits]
post_data_request = 10000000
report_result = 2000000

[storage]
# Path of the folder where RocksDB storage files will be written to.
db_path = ".witnet_bridge/storage"
