# You can read more about all the configuration params in
# https://docs.witnet.io/configuration/toml-file/
[connections]
# Server address tells what local interface and port the Witnet node server should bind to.
# This will probably look like `0.0.0.0:21337` or `192.168.x.x:21337`, but it totally depends on your local network.
server_addr = "0.0.0.0:21337"
# Public address needs to match your *public* IP and port, assuming your router is configured to forward incoming
# connections to the local IP of the device the node is running. Failure to configure this setting will result in your
# node not receiving inbound connections (see: https://docs.witnet.io/try/run-a-node/#open-your-ports).
public_addr = "0.0.0.0:21337"
known_peers = [
    "52.166.178.145:21337",
    "46.6.7.37:21337",
    "94.130.108.133:21337",
    "46.25.5.131:21337",
    "138.201.173.154:21337",
    "95.217.22.79:21337",
    "78.47.148.22:21337",
    "173.212.199.96:21337",
    "45.32.127.187:21337",
    "167.86.89.36:21337",
    "144.91.114.154:21337",
    "173.212.214.124:21337",
    "47.254.173.135:21337",
    "8.209.65.253:21337",
    "207.61.234.35:21337",
    "76.170.96.97:21337",
    "144.91.73.85:21337",
    "18.140.218.49:21337",
    "79.152.202.140:21337",
    "51.15.121.63:21337",
    "167.86.102.170:21337",
    "51.83.93.209:21337",
    "167.86.116.89:21337",
    "173.212.212.43:21337",
    "164.68.100.118:21337",
    "144.217.204.0:21337",
    "167.86.76.5:21337",
    "217.254.186.98:21337",
    "73.153.225.122:21337",
    "41.212.58.87:21337",
    "144.202.100.245:21337"
]
outbound_limit = 8
bootstrap_peers_period_seconds = 1

[storage]
db_path = ".witnet/storage"

[jsonrpc]
enabled = true
server_address = "127.0.0.1:21338"

[consensus_constants]
checkpoints_period = 45
# Tuesday, 28-Apr-2020, 9:00 UTC
checkpoint_zero_timestamp = 1590055200
bootstrap_hash = "00000000000000000000000000000000000000007769746e65742d302e382e31"
genesis_hash = "5569132f8c5a9db05cbb50adaf6d840fbe39a07d86bbef5fc3d2867562f0de9d"
activity_period = 1000
collateral_age = 1000

[ntp]
update_period_seconds = 8000000

[mining]
enabled = true
data_request_max_retrievals_per_epoch = 30
data_request_timeout_milliseconds = 2000
genesis_path = ".witnet/config/genesis_block.json"
# `mint_external_address` and `mint_external_percentage` enable splitting the mint reward between the node's
# own address and an "external" address, e.g. a the address of a wallet. `mint_external_percentage` indicates
# the percentage of the block rewards that will be assigned to `mint_external_address` (50% by default)
#mint_external_address = "twit1jqgf4rxjrgas3kdhj3t4cr3mg3n33m8zw0aulr"
#mint_external_percentage = 50

[log]
# Logging level, i.e. from more verbose to quieter: "trace" > "debug" > "info" > "warn" > "error" > "none"
level = "debug"
# Automated bug reporting (helps the community improve the software)
sentry_telemetry = true

[wallet]
testnet = true
node_url = "127.0.0.1:21338"
