# You can read more about all the configuration params in
# https://docs.witnet.io/configuration/toml-file/
[connections]
server_addr = "0.0.0.0:21337"
known_peers = ["52.166.178.145:21337"]
outbound_limit = 1
bootstrap_peers_period_seconds = 15

[storage]
db_path = ".witnet-rust-testnet-3"

[consensus_constants]
checkpoint_zero_timestamp = 1559347200
