[connections]
server_addr = "0.0.0.0:21337"

[storage]
db_path = ".wit"

[consensus_constants]
checkpoint_zero_timestamp = 1542203073

#########################################
### LOGGING CONFIGURATION             ###
#########################################

[logging]

# Whether to log to stdout
log_to_stdout = true

# Log level for stdout: Critical, Error, Warning, Info, Debug, Trace
stdout_log_level = "Debug"

# Whether to log to a file
log_to_file = true

# Log level for file: Critical, Error, Warning, Info, Debug, Trace
file_log_level = "Debug"

# Log file path
log_file_path = "wit.log"

# Whether to append to the log file (true), or replace it on every run (false)
log_file_append = true
