[package]
name = "witnet_rad"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
edition = "2018"
workspace = ".."
description = "RAD component"

[dependencies]
witnet_crypto = { path = "../crypto" }
witnet_data_structures = { path = "../data_structures" }
witnet_util = { path = "../util" }
failure = "0.1.5"
json = "0.11.13"
log = "0.4.6"
num-derive = "0.2.3"
num-traits = "0.2.6"
rmp = "0.8.7"
rmpv = "0.4.0"