[package]
name = "witnet_rad"
version = "0.3.2"
authors = ["Witnet Foundation <info@witnet.foundation>"]
edition = "2018"
workspace = ".."
description = "RAD component"

[dependencies]
failure = "0.1.5"
hex = "0.3.2"
json = "0.11.13"
log = "0.4.6"
num-derive = "0.2.4"
num-traits = "0.2.6"
reqwest = "=0.9.17"
rust-crypto = "0.2.36"
serde_cbor = "0.10.1"
witnet_crypto = { path = "../crypto" }
witnet_data_structures = { path = "../data_structures" }
witnet_util = { path = "../util" }
serde = "1.0.91"
itertools = "0.8.0"

