[package]
name = "witnet_rad"
version = "0.3.2"
authors = ["Witnet Foundation <info@witnet.foundation>"]
edition = "2018"
workspace = ".."
description = "RAD component"

[dependencies]
failure = "0.1.6"
hex = "0.4.0"
json = "0.12.0"
log = "0.4.8"
num-derive = "0.3.0"
num-traits = "0.2.8"
reqwest = "0.9.22"
rust-crypto = "0.2.36"
serde_cbor = "0.10.2"
witnet_crypto = { path = "../crypto" }
witnet_data_structures = { path = "../data_structures" }
witnet_util = { path = "../util" }
serde = "1.0.101"
itertools = "0.8.0"

