[package]
name = "witnet_rad"
version = "0.1.2"
authors = ["Witnet Foundation <info@witnet.foundation>"]
edition = "2018"
workspace = ".."
description = "RAD component"

[dependencies]
failure = "0.1.5"
hex = "0.3.2"
json = "0.11.13"
log = "0.4.6"
num-derive = "0.2.4"
num-traits = "0.2.6"
reqwest = "0.9.10"
rmp = "0.8.7"
rmpv = "0.4.0"
rust-crypto = "0.2.36"
witnet_crypto = { path = "../crypto" }
witnet_data_structures = { path = "../data_structures" }
witnet_util = { path = "../util" }

