[package]
authors = ["Witnet Foundation <info@witnet.foundation>"]
edition = "2018"
name = "witnet_wallet"
version = "0.3.2"
workspace = ".."

[dependencies]
async-jsonrpc-client = { git = "https://github.com/witnet/async-jsonrpc-client", features = ["tcp"] }
bincode = "1.2.0"
log = "0.4.8"
jsonrpc-core = "14.0.1"
futures = "0.1.29"
serde = { version = "1.0.101", features = ["derive", "rc"] }
serde_json = "1.0.41"
rocksdb = "0.13.0"
rayon = "1.2.0"
num_cpus = "1.10.1"
jsonrpc-pubsub = "14.0.1"
actix = "0.8.3"
tokio-signal = "0.2.7"
failure = "0.1.6"
hex = "0.4.0"
rand = "0.7.2"
hamt-rs = "0.3.0"
chrono = "0.4.9"

witnet_net = { path = "../net" }
witnet_config = { path = "../config", features = ["with-rocksdb"] }
witnet_storage = { path = "../storage" }
witnet_rad = { path = "../rad" }
witnet_crypto = { path = "../crypto", features = ["with-serde"] }
witnet_protected = { path = "../protected", features = ["with-serde"] }
witnet_data_structures = { path = "../data_structures" }
witnet_validations = { path = "../validations" }
