[package]
authors = ["Witnet Foundation <info@witnet.foundation>"]
edition = "2018"
name = "witnet_wallet"
version = "0.3.0"
workspace = ".."

[dependencies]
async-jsonrpc-client = { git = "https://github.com/witnet/async-jsonrpc-client", features = ["tcp"] }
bincode = "1.1.3"
log = "0.4.6"
env_logger = "0.6.1"
jsonrpc-core = "11.0.0"
futures = "0.1.26"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
clap = "2.33.0"
rocksdb = "0.12.2"
failure = "0.1.5"
rayon = "1.0.3"
num_cpus = "1.10.0"
jsonrpc-pubsub = "11.0.0"
actix = "0.8.3"

witnet_net = { path = "../net" }
witnet_config = { path = "../config" }
witnet_storage = { path = "../storage" }
witnet_rad = { path = "../rad" }
witnet_crypto = { path = "../crypto" }
witnet_data_structures = { path = "../data_structures" }
tokio-signal = "0.2.7"
