[package]
authors = ["Witnet Foundation <info@witnet.foundation>"]
edition = "2018"
name = "witnet_wallet"
version = "0.1.2"
workspace = ".."

[dependencies]
actix = "0.7.9"
bip39 = "0.6.0-beta.1"
env_logger = "0.6.0"
failure = "0.1.5"
futures = "0.1.25"
hmac = "*"
log = "0.4.6"
tiny-hderive = "*"
jsonrpc-ws-server = "10.1.0"
secp256k1 = "*"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.38"
sha2 = "*"
async-jsonrpc-client = { git = "https://github.com/witnet/async-jsonrpc-client", features = ["tcp"] }
