[package]
authors = ["Witnet Foundation <info@witnet.foundation>"]
description = "data structures component"
edition = "2018"
name = "witnet_data_structures"
version = "0.1.0"
workspace = ".."

[dependencies]
byteorder = "1.2.6"
protobuf-convert = "0.1.0"
failure = "0.1.5"
protobuf = { version = "2.2.0", features = ["with-serde"] }
rand = "0.5.5"
serde = "1.0.79"
serde_derive = "1.0.79"
toml = "0.4.6"

[dependencies.partial_struct]
path = "../partial_struct"

[dependencies.witnet_crypto]
path = "../crypto"

[dependencies.witnet_util]
path = "../util"

[build-dependencies]
exonum-build = "0.10.0"
