[package]
authors = ["Witnet Foundation <info@witnet.foundation>"]
description = "data structures component"
edition = "2018"
name = "witnet_data_structures"
version = "0.3.2"
workspace = ".."

[dependencies]
byteorder = "1.3.1"
failure = "0.1.5"
protobuf = { version = "2.3.0", features = ["with-serde"] }
protobuf-convert = "0.1.1"
rand = "0.6.5"
toml = "0.4.10"
log = "0.4.6"
secp256k1 = "0.12.2"
vrf = "0.2.0"
witnet_reputation = { path = "../reputation", features = ["serde"] }
witnet_protected = { path = "../protected" }

[dependencies.partial_struct]
path = "../partial_struct"

[dependencies.witnet_crypto]
path = "../crypto"

[dependencies.witnet_util]
path = "../util"

[build-dependencies]
exonum-build = "0.10.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.88"
