[package]
name = "witnet_protected"
version = "0.2.1"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "Protected bytes struct that will be zeroed when dropped"
edition = "2018"

[dependencies]
memzero = "0.1.0"
