[package]
name = "witnet_p2p"
version = "0.2.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "p2p component"
edition = "2018"

[dependencies]
failure = "0.1.5"
rand = "0.6.5"
witnet_util = { path = "../util" }

[dependencies.serde]
features = ["derive"]
version = "1.0.88"
