[package]
name = "witnet_core"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "core component"
edition = "2018"

[dependencies]
actix = "0.7.4"
log = "0.4.5"
futures = "0.1"
tokio = "0.1.11"
bytes = "0.4"
rand = "0.5.5"
witnet_storage = { path = "../storage" }
witnet_p2p = { path = "../p2p" }
witnet_util = { path = "../util" }
