[package]
name = "witnet_storage"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
edition = "2018"
description = "Witnet storage module that conveniently abstracts a key/value API away from specific storage backends"

[dependencies]
env_logger = "0.6.0"
failure = "0.1.5"
log = "0.4.6"
serde_json = "1.0.38"
rocksdb = { version = "0.11.0", optional = true }
serde = "1.0.88"
witnet_util = { path = "../util" }

[features]
rocksdb-backend = ["rocksdb"]
