[package]
authors = ["Witnet Foundation <info@witnet.foundation>"]
description = "config component"
edition = "2018"
name = "witnet_config"
version = "0.3.2"
workspace = ".."

[features]
with-rocksdb = ["rocksdb"]

[dependencies]
failure = "0.1.6"
log = "0.4.8"
toml = "0.5.3"
partial_struct = { path = "../partial_struct" }
serde = { version = "1.0.101", features = ["derive"] }
directories = "2.0.2"
rocksdb = { version = "0.12.4", optional = true }

witnet_data_structures = { path = "../data_structures" }
witnet_protected = { path = "../protected" }
witnet_crypto = { path = "../crypto", features = ["with-serde"] }
