[package]
name = "witnet_config"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "config component"
edition = "2018"

[dependencies]
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.28"
toml = "0.4.6"
