[package]
name = "witnet_config"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "config component"

[dependencies]
serde_json = "1.0.28"
toml = "0.4.6"