[package]
authors = ["Witnet Foundation <info@witnet.foundation>"]
description = "config component"
edition = "2018"
name = "witnet_config"
version = "0.1.0"
workspace = ".."

[dependencies]
failure = "0.1.2"
log = "0.4"
toml = "0.4.6"
partial_struct = { path = "../partial_struct" }

[dependencies.serde]
features = ["derive"]
version = "1.0.82"

[dependencies.witnet_data_structures]
path = "../data_structures"

[dependencies.witnet_util]
path = "../util"
