[package]
name = "witnet_config"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "config component"
edition = "2018"

[dependencies]
log = "0.4"
serde = "1.0.79"
serde_derive = "1.0.79"
toml = "0.4.6"
failure = "0.1.2"
witnet_util = { path = "../util" }
