[package]
name = "witnet_node"
version = "0.2.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "node component"
edition = "2018"

[dependencies]
ansi_term = "0.11.0"
byteorder = "1.3.1"
bytes = "0.4.11"
failure = "0.1.2"
futures = "0.1.25"
jsonrpc-core = "10.1.0"
jsonrpc-pubsub = "10.1.0"
log = "0.4.6"
rand = "0.6.5"
rust-crypto = "0.2.36"
serde = "1.0.88"
serde_json = "1.0.38"
tokio = "0.1.15"
secp256k1 = "0.12.2"

witnet_data_structures = { path = "../data_structures" }
witnet_p2p = { path = "../p2p" }
witnet_storage = { path = "../storage", features = ["rocksdb-backend", "crypto-backend"] }
witnet_config = { path = "../config" }
witnet_util = { path = "../util" }
witnet_crypto = { path = "../crypto" }
witnet_rad = { path = "../rad" }
witnet_wallet = { path = "../wallet" }
witnet_validations = { path = "../validations" }

[dependencies.actix]
git = "https://github.com/actix/actix.git"
rev = "d28d286ac652f81e72c2aa413e7c0d3fc6c6099c"
