[package]
name = "witnet_crypto"
version = "0.1.2"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "crypto component"
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
