[package]
name = "witnet_crypto"
version = "0.1.2"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "crypto component"
edition = "2018"

[dependencies]
tiny-bip39 = "0.6.0"
failure = "0.1.5"
rust-crypto = "0.2.36"
secp256k1 = "0.12.2"