name: Push checks

on: [push]

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    env:
      ROCKSDB_LIB_DIR: /usr/lib/
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:maarten-fonville/protobuf
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-5 cmake libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev protobuf-compiler librocksdb-dev
          just || curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git casey/just --target x86_64-unknown-linux-musl --to ~/.cargo/bin

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: just ci
