[package]
name = "witnet_net"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
edition = "2018"
workspace = ".."

[dependencies]
failure = "0.1.6"
futures = "0.1.29"
log = "0.4.8"
env_logger = "0.7.1"
jsonrpc-core = "14.0.1"
async-jsonrpc-client = { git = "https://github.com/witnet/async-jsonrpc-client", features = ["tcp"] }
tokio = "0.1.22"
serde_json = "1.0.41"
serde = "1.0.101"
jsonrpc-ws-server = "14.0.1"
jsonrpc-pubsub = "14.0.1"
actix = "0.8.3"
