[package]
name = "witnet_net"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
edition = "2018"
workspace = ".."

[dependencies]
failure = "0.1.5"
futures = "0.1.26"
log = "0.4.6"
env_logger = "0.6.1"
jsonrpc-core = "11.0.0"
async-jsonrpc-client = { git = "https://github.com/witnet/async-jsonrpc-client", features = ["tcp"] }
tokio = "0.1.20"
serde_json = "1.0.39"
serde = "1.0.91"
jsonrpc-ws-server = "11.0.0"
jsonrpc-pubsub = "11.0.0"
actix = "0.8.3"
